targets:
  # - name: obs
  #   address: localhost:4444
  #   password: <OBS_REMOTE_PASSWORD>
  # - name: shell
  # - name: philipshue
  #   host: <PHILIPS_HUE_HOST>
  #   username: <PHILIPS_HUE_TOKEN>
